# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Biografía
    url: '#about'
    weight: 10
  - name: Proyectos
    url: '#projects'
    weight: 30
  - name: Tesis
    url: '#talks'
    weight: 40
  - name: Publicaciones
    url: '#public-recents'
    weight: 50
  - name: Docencia
    url: '#docenc'
    weight: 60

# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/uploads/resume.pdf` and uncomment the lines below.
#  - name: CV
#    url: uploads/resume.pdf
#    weight: 70
